export const GET_USER ="GET_USER";
export const DELETE_USER ="DELETE_USER";
export const ADD_USER ="ADD_USER";
export const UPDATE_USER ="UPDATE_USER";
export const GET_SINGLE_USER ="GET_SINGLE_USER";

export const GET_EMPLOYEE ="EMPLOYEE";
export const DELETE_EMPLOYEE ="DELETE_EMPLOYEE";
export const ADD_EMPLOYEE ="ADD_EMPLOYEE";
export const UPDATE_EMPLOYEE ="UPDATE_EMPLOYEE";
export const GET_SINGLE_EMPLOYEE ="GET_SINGLE_EMPLOYEE";
